# Generated by Django 5.0.6 on 2024-06-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_especialidad_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
